import Header from "./Header";
import "./globals.css";
import Providers from "./providers/Providers";

export const metadata = {
  title: "Chrono Press",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body className="bg-gray-100 dark:bg-zinc-900 transition-all duration-200">
      <Providers>
          <Header />
          <div className="max-w-6xl mx-auto">{children}</div>
      </Providers>
        </body>
    </html>
  );
}
